using System.ComponentModel.DataAnnotations;

namespace TechnicalRadiation.Models.InputModels
{
    public class CategoryInputModel
    {
        [Required]
        [MaxLength(60)]
        public string Name { get; set; }
        
        //default to 0
        public int ParentCategoryId { get; set; }

        //should be generated by making the name lowercase and join the words together
        //with a hyphen (-), e.g. Science Fiction will be science-fiction
        public string Slug { get; set; }
    }
}